#!/usr/bin/env bash
# Generate ed25519 SSH keypairs for the edge node and store them safely:
#   secrets/ssh/<name>_ed25519.sops  private key, SOPS/age-encrypted (committed)
#   secrets/ssh/<name>_ed25519.pub   public key, plaintext (committed)
# then regenerate ansible/inventories/prod/group_vars/all/ssh_public_keys.yml.
#
# The plaintext private key exists only in a 0700 tmpfs directory for the
# duration of the encryption and is removed on exit. Existing keys are never
# overwritten (rotation = delete both files deliberately, then re-run).
#
# Usage: scripts/seed-ssh-keys.sh operator ci
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
key_dir="${repo_root}/secrets/ssh"
vars_file="${repo_root}/ansible/inventories/prod/group_vars/all/ssh_public_keys.yml"

command -v sops >/dev/null || { echo "sops not on PATH (run: make deps)" >&2; exit 1; }
command -v ssh-keygen >/dev/null || { echo "ssh-keygen not found" >&2; exit 1; }
[[ $# -ge 1 ]] || { echo "usage: $0 <name>..." >&2; exit 2; }

if grep -q 'REPLACE_WITH_' "${repo_root}/.sops.yaml"; then
  echo ".sops.yaml still has placeholder age recipients; refusing to generate keys." >&2
  exit 1
fi

tmp_base=/dev/shm
[[ -d "${tmp_base}" && -w "${tmp_base}" ]] || tmp_base="${TMPDIR:-/tmp}"
umask 077
work="$(mktemp -d "${tmp_base}/seed-ssh.XXXXXX")"
cleanup() {
  find "${work}" -type f -exec sh -c 'command -v shred >/dev/null && shred -u "$1" || rm -f "$1"' _ {} \; 2>/dev/null || true
  rm -rf "${work}"
}
trap cleanup EXIT INT TERM

mkdir -p "${key_dir}"
for name in "$@"; do
  [[ "${name}" =~ ^[a-z][a-z0-9-]{0,30}$ ]] || { echo "invalid key name: ${name}" >&2; exit 2; }
  enc="${key_dir}/${name}_ed25519.sops"
  pub="${key_dir}/${name}_ed25519.pub"
  if [[ -e "${enc}" || -e "${pub}" ]]; then
    echo "skip ${name}: already exists"
    continue
  fi
  ssh-keygen -q -t ed25519 -a 100 -N '' -C "homelab-edge-${name}" -f "${work}/${name}"
  rel="${enc#"${repo_root}/"}"
  (cd "${repo_root}" && sops --encrypt --input-type binary --output-type binary \
      --filename-override "${rel}" "${work}/${name}") > "${enc}.tmp"
  mv "${enc}.tmp" "${enc}"
  install -m 0644 "${work}/${name}.pub" "${pub}"
  # Prove the round trip before trusting the encrypted copy.
  (cd "${repo_root}" && sops --decrypt --input-type binary --output-type binary "${rel}") \
    | ssh-keygen -y -f /dev/stdin | cut -d' ' -f1,2 \
    | diff -q - <(cut -d' ' -f1,2 "${pub}") >/dev/null \
    || { echo "round-trip verification failed for ${name}" >&2; rm -f "${enc}" "${pub}"; exit 1; }
  echo "created ${name}: $(ssh-keygen -lf "${pub}")"
done

{
  echo "---"
  echo "# GENERATED by scripts/seed-ssh-keys.sh from secrets/ssh/*.pub. Do not edit."
  echo "admin_ssh_public_keys:"
  for p in "${key_dir}"/*_ed25519.pub; do
    [[ -e "${p}" ]] || continue
    printf '  - "%s"\n' "$(cat "${p}")"
  done
} > "${vars_file}"
echo "wrote ${vars_file#"${repo_root}/"}"
